# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('assigned_task', models.TextField()),
                ('completed_task', models.TextField()),
                ('pub_date', models.DateField()),
                ('status', models.CharField(choices=[('n', 'New'), ('o', 'Ongoing'), ('c', 'Completed')], max_length=1)),
            ],
        ),
    ]
