# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_task',
        ),
    ]
