# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_records', '0004_auto_20170605_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to_employee',
        ),
    ]
