# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('employee_records', '0009_auto_20170605_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
    ]
