# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_records', '0011_auto_20170605_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Group Name'),
        ),
    ]
