# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_records', '0013_auto_20170605_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to_employee',
            new_name='assign_to_employee',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to_group',
            new_name='assign_to_group',
        ),
    ]
