# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_records', '0014_auto_20170605_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
