# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_records', '0015_auto_20170606_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign_to_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
