# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_records', '0016_auto_20170606_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('n', 'new'), ('o', 'ongoing'), ('c', 'completed')], max_length=1),
        ),
    ]
