# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_records', '0017_auto_20170606_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_task',
            new_name='content',
        ),
    ]
