# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_records', '0018_auto_20170606_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Due Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateField(verbose_name='Assigned on:'),
        ),
    ]
