# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_records', '0019_auto_20170606_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='group',
        ),
    ]
