# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('employee_records', '0020_auto_20170607_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='group',
        ),
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.ManyToManyField(max_length=100, to='auth.Group'),
        ),
    ]
