# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('employee_records', '0021_auto_20170609_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='group',
        ),
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.ForeignKey(default=1, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='task',
            name='assign_to_employee',
        ),
        migrations.AddField(
            model_name='task',
            name='assign_to_employee',
            field=models.ManyToManyField(to='employee_records.Employee'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='assign_to_group',
        ),
        migrations.AddField(
            model_name='task',
            name='assign_to_group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
