# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_records', '0022_auto_20170609_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(default='1900-09-23'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
