# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_records', '0024_auto_20170609_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='group',
        ),
    ]
