# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('employee_records', '0025_remove_employee_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.ForeignKey(default=1, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Department'),
            preserve_default=False,
        ),
    ]
