# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_records', '0026_employee_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign_to_group',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
