# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_records', '0027_auto_20170609_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('n', 'new'), ('o', 'ongoing'), ('c', 'completed')], default='n', max_length=1),
        ),
    ]
